spring:
  data:
    redis:
      host: ${LSF_REDIS_HOST:redis}
      port: ${LSF_REDIS_PORT:6379}

lsf:
  kafka:
    bootstrap-servers: ${LSF_KAFKA_BOOTSTRAP_SERVERS:kafka:29092}
    schema-registry-url: ${LSF_SCHEMA_REGISTRY_URL:http://schema-registry:8081}

management:
  tracing:
    zipkin:
      tracing:
        endpoint: ${LSF_ZIPKIN_ENDPOINT:http://zipkin:9411/api/v2/spans}
